name: Blog Update Notification

on:
  push:
    branches:
    - main

jobs:
  notify-subscribers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Detect Changes
      run: |
        #!/bin/bash
    
        # Fetch the last two commits
        git fetch --depth=2
    
        # Debug: Check the last two commit IDs
        echo "Last two commits:"
        git log -n 2 --pretty=format:"%H"
    
        # Debug: Output the raw diff to check if it's working
        echo "Raw diff output:"
        git diff --name-status HEAD^ HEAD
    
        # Initialize an empty variable to store changed files
        changed_files=""
    
        # Use a subshell to capture output of git diff and grep
        # The '|| true' ensures that the command doesn't cause an error exit
        changed_files=$(git diff --name-status HEAD^ HEAD | grep -E '\.md$|\.mdx$' || true)
    
        # Check if there are any MD/MDX files
        if [ -z "$changed_files" ]; then
          echo "No MD/MDX files changed"
          exit 0  # Exit with a success status
        fi
        
        # Check if there are any MD/MDX files
        if [ -z "$changed_files" ]; then
          echo "No MD/MDX files changed"
          exit 0  # Exit with a success status
        fi
        
        # # Debug: Output the filtered diff result
        # echo "Filtered diff output (MD/MDX files):"
        # echo "$changed_files"

    - name: Send Email via ConvertKit
      env:
        CONVERTKIT_API_KEY: ${{ secrets.CONVERTKIT_API_KEY }}
      run: |
        # Add your script/command to send emails using ConvertKit's API
