name: Blog Update Notification

on:
  push:
    branches:
      - main

jobs:
  notify-subscribers:
    runs-on: ubuntu-latest
    steps:
      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v2

      - id: set_up_nodejs
        name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - id: detect_article_changes
        name: Detect article changes
        run: bash ./.github/workflows/detect_article_changes.sh

      # - id: check_article_data
      #   name: Check article data
      #   env:
      #     ARTICLE_DATA: ${{ steps.detect_article_changes.outputs.article_data }}
      #   run: bash ./.github/workflows/check_article_data.sh

      - id: send_email
        name: Send Email via ConvertKit
        if: ${{ env.ARTICLE_DATA }}
        env:
          ARTICLE_DATA: ${{ steps.detect_article_changes.outputs.article_data }}
          # ARTICLE_READY: ${{ env.ARTICLE_READY }}
          CONVERTKIT_API_KEY: ${{ secrets.CONVERTKIT_API_KEY }}
          CONVERTKIT_API_BASE_URL: ${{ vars.CONVERTKIT_API_BASE_URL }}
          CONVERTKIT_API_BROADCASTS_ENDPOINT: \
            ${{ vars.CONVERTKIT_API_BROADCASTS_ENDPOINT }}
        run: bash ./.github/workflows/send_email.sh
