name: Blog Update Notification

on:
  push:
    branches:
      - main

jobs:
  notify-subscribers:
    runs-on: ubuntu-latest
    steps:
      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          sparse-checkout: |
            .github
            src/app/articles
          sparse-checkout-cone-mode: false

      - id: set_up_nodejs
        name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # - id: detect_article_changes
      #   name: Detect article changes
      #   run: bash ./.github/workflows/detect_article_changes.sh

      # - id: check_commit
      #   name: Check commit message
      #   run: |
      #     commit_message=$(git log -1 --pretty=%B)
      #     echo "commit_message=$commit_message" >> $GITHUB_ENV
      #     if [[ "$commit_message" == *"[CK-Broadcast]"* ]]; then
      #       echo "SEND_NOTIFICATION=true" >> $GITHUB_ENV
      #     else
      #       echo "SEND_NOTIFICATION=false" >> $GITHUB_ENV
      #     fi

      - id: extract_article_path
        name: Extract article path
        run: bash ./.github/workflows/extract_article_path.sh

      - id: send_ck_email
        name: Send email via ConvertKit
        if: ${{ env.ARTICLE_PATH }}
        env:
          ARTICLE_PATH: ${{ steps.extract_article_path.outputs.article_path }}
          CK_API_KEY: ${{ secrets.CK_API_KEY }}
          CK_API_BASE_URL: ${{ vars.CK_API_BASE_URL }}
          CK_API_BROADCASTS_ENDPOINT: ${{ vars.CK_API_BROADCASTS_ENDPOINT }}
        run: bash ./.github/workflows/send_ck_email.sh
