name: Blog Update Notification

on:
  push:
    branches:
    - main

jobs:
  notify-subscribers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Detect Changes
      run: |
        #!/bin/bash
    
        # Fetch the last two commits
        git fetch --depth=2
    
        # Debug: Check the last two commit IDs
        echo "Last two commits:"
        git log -n 2 --pretty=format:"%H"
    
        # Debug: Output the raw diff to check if it's working
        echo "Raw diff output:"
        git diff --name-status HEAD^ HEAD
    
        # Get the file changes between the last two commits
        changed_files=$(git diff --name-status HEAD^ HEAD | grep -E '\.md$|\.mdx$')
    
        # # Debug: Output the filtered diff result
        # echo "Filtered diff output (MD/MDX files):"
        # echo "$changed_files"

    - name: Send Email via ConvertKit
      env:
        CONVERTKIT_API_KEY: ${{ secrets.CONVERTKIT_API_KEY }}
      run: |
        # Add your script/command to send emails using ConvertKit's API
