name: Blog Update Notification

on:
  push:
    branches:
      - main

jobs:
  notify-subscribers:
    runs-on: ubuntu-latest
    steps:
      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          sparse-checkout: |
            .github
            src/app/articles
          sparse-checkout-cone-mode: false

      - id: check_commit_for_broadcast
        name: Check commit for broadcast
        run: bash ./.github/workflows/check_commit_for_broadcast.sh

      - id: set_up_nodejs
        name: Set up Node.js
        uses: actions/setup-node@v4.0.1
        env:
          ARTICLE_PATH: ${{ steps.check_commit_for_broadcast.outputs.article_path }}
        if: ${{ env.ARTICLE_PATH }}
        with:
          node-version: '21.6.1'

      - id: install_workflow_packages
        name: Install workflow packages
        env:
          ARTICLE_PATH: ${{ steps.check_commit_for_broadcast.outputs.article_path }}
        if: ${{ env.ARTICLE_PATH }}
        run: npm install js-yaml chalk

      - id: parse_front_matter
        name: Parse front matter
        uses: actions/github-script@v7.0.1
        env:
          ARTICLE_PATH: ${{ steps.check_commit_for_broadcast.outputs.article_path }}
        if: ${{ env.ARTICLE_PATH }}
        with:
          script: |
            const parseFrontMatter = import('./.github/workflows/parseFrontMatter.js')
            return parseFrontMatter({github, context})

      - id: send_ck_email
        name: Send email via ConvertKit
        uses: actions/github-script@v7.0.1
        env:
          ARTICLE_FRONT_MATTER: ${{ steps.parse_front_matter.outputs.result }}
          CK_API_KEY: ${{ secrets.CK_API_KEY }}
          CK_API_BASE_URL: ${{ vars.CK_API_BASE_URL }}
          CK_API_BROADCASTS_ENDPOINT: ${{ vars.CK_API_BROADCASTS_ENDPOINT }}
        if: ${{ env.ARTICLE_FRONT_MATTER }}
        with:
          script: |
            const script = require('./.github/workflows/sendCkEmail.js')
            console.log(script({github, context}))
